name: uploadTestFlight

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Run Fastlane QA
        run: fastlane QA
        working-directory: ./OPeace
        env:
          APP_NAME: "OPeace"
          SCHEME: "OPeace-QA"
          TEAM_ID: ${{ secrets.TEAM_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          SLACK_URL_UPLOAD: ${{ secrets.SLACK_URL_UPLOAD }}
